import type { Certification, LearningPath, PlaygroundExercise, Resource, Skill } from "@/lib/types";

export const skills: Skill[] = [
  {
    id: "intro-ai-engineering",
    title: "Introducción a AI Engineering",
    slug: "introduccion-ai-engineering",
    category: "Fundamentos de IA",
    level: "beginner",
    description: "Diferencia AI Engineer, ML Engineer y AI Architect; ubica el rol en producto, backend y plataforma.",
    whyItMatters: "Evita estudiar IA como si todo fuera entrenar modelos desde cero. El foco real del AI Engineer moderno es integrar modelos, evaluar calidad y llevar capacidades a producción.",
    prerequisites: ["Fundamentos de programación", "HTTP y APIs", "Git básico"],
    learn: ["LLMs, inferencia y entrenamiento", "Embeddings", "RAG", "Agentes", "Riesgos de seguridad y privacidad"],
    exercises: ["Mapea una app existente y marca dónde usarías IA", "Escribe una ficha comparando AI Engineer vs ML Engineer"],
    resources: ["Roadmap AI Engineer de roadmap.sh", "Hugging Face AI Agents Course", "Google Machine Learning Crash Course"],
    certifications: ["Google Cloud Digital Leader"],
    cloudMappings: [{ concept: "Plataforma IA", gcp: "Vertex AI", aws: "Amazon Bedrock / SageMaker", azure: "Azure AI Foundry", local: "Ollama + Docker" }],
    nextSkills: ["python-ai", "llm-inference"],
    position: { x: 180, y: 20 },
  },
  {
    id: "python-ai",
    title: "Python para IA aplicada",
    slug: "python-para-ia",
    category: "Python para IA",
    level: "beginner",
    description: "Python práctico para consumir APIs, procesar datos, crear notebooks reproducibles y empaquetar utilidades.",
    whyItMatters: "Python sigue siendo el idioma común para prototipos, embeddings, evaluación, notebooks y automatización de pipelines de IA.",
    prerequisites: ["Programación básica", "Entornos virtuales"],
    learn: ["FastAPI", "Pydantic", "pandas", "pytest", "Jupyter", "gestión de secretos"],
    exercises: ["Crea un script que normalice documentos Markdown", "Publica una API FastAPI que calcule embeddings mock"],
    resources: ["FastAPI docs", "Pydantic docs", "Python Packaging User Guide"],
    certifications: ["DeepLearning.AI Machine Learning Specialization"],
    cloudMappings: [{ concept: "Runtime", gcp: "Cloud Run", aws: "Lambda / ECS Fargate", azure: "Container Apps", local: "Docker Compose" }],
    nextSkills: ["backend-ai", "embeddings"],
    position: { x: 180, y: 160 },
  },
  {
    id: "backend-ai",
    title: "Backend para productos con IA",
    slug: "backend-ai",
    category: "Backend para IA",
    level: "intermediate",
    description: "Diseño de APIs serverless, contratos tipados, streaming, colas, rate limits y trazabilidad para features con LLMs.",
    whyItMatters: "La IA en producción se parece mucho a backend serio: latencia, costos, errores parciales, seguridad, observabilidad y límites de proveedor.",
    prerequisites: ["Python o TypeScript", "REST", "bases de datos"],
    learn: ["Route Handlers", "streaming", "webhooks", "colas", "caché", "idempotencia"],
    exercises: ["Diseña una API de chat con streaming", "Implementa límites por usuario y logging de costo por request"],
    resources: ["Next.js Route Handlers", "Vercel Functions docs", "OpenTelemetry docs"],
    certifications: ["AWS Certified Developer - Associate", "Azure Developer Associate"],
    cloudMappings: [{ concept: "Serverless API", gcp: "Cloud Functions / Cloud Run", aws: "Lambda + API Gateway", azure: "Azure Functions", local: "Node.js + Docker" }],
    nextSkills: ["llm-inference", "rag"],
    position: { x: 180, y: 300 },
  },
  {
    id: "llm-inference",
    title: "LLMs e inferencia",
    slug: "llms-inferencia",
    category: "Fundamentos de IA",
    level: "beginner",
    description: "Uso de modelos preentrenados, ventanas de contexto, tokens, latencia, temperatura, límites y tradeoffs.",
    whyItMatters: "Elegir y operar un modelo implica entender calidad, costo, contexto, seguridad y experiencia de usuario.",
    prerequisites: ["Introducción a AI Engineering"],
    learn: ["Modelos abiertos vs cerrados", "context length", "tokenización", "batching", "fallbacks", "costo por inferencia"],
    exercises: ["Compara tres modelos para un caso de soporte interno", "Construye una tabla de costo/latencia/calidad"],
    resources: ["Hugging Face Open LLM Leaderboard", "Ollama model library", "LMSYS Chatbot Arena"],
    certifications: ["NVIDIA Generative AI LLMs"],
    cloudMappings: [{ concept: "Model serving", gcp: "Vertex AI Model Garden", aws: "Bedrock", azure: "Azure AI Model Catalog", local: "Ollama / vLLM" }],
    nextSkills: ["prompt-engineering", "ai-safety"],
    position: { x: 540, y: 90 },
  },
  {
    id: "prompt-engineering",
    title: "Prompt Engineering práctico",
    slug: "prompt-engineering",
    category: "RAG",
    level: "beginner",
    description: "Patrones para instrucciones, contexto, formatos de salida, few-shot examples y pruebas sistemáticas.",
    whyItMatters: "El prompt es parte del contrato de producto. Debe versionarse, probarse y protegerse contra entradas hostiles.",
    prerequisites: ["LLMs e inferencia"],
    learn: ["system prompts", "few-shot", "structured output", "prompt injection", "prompt evals"],
    exercises: ["Crea prompts versionados para clasificar tickets", "Diseña 20 pruebas de regresión para un asistente"],
    resources: ["Prompt Engineering Guide", "OWASP Top 10 for LLM Applications"],
    certifications: ["DeepLearning.AI Prompt Engineering for Developers"],
    cloudMappings: [{ concept: "Prompt registry", gcp: "Vertex AI Prompt Management", aws: "Bedrock Prompt Management", azure: "Prompt flow", local: "Git + JSON/YAML" }],
    nextSkills: ["embeddings", "ai-safety"],
    position: { x: 540, y: 230 },
  },
  {
    id: "ai-safety",
    title: "Seguridad, privacidad y evaluación",
    slug: "seguridad-privacidad-evaluacion",
    category: "LLMOps",
    level: "intermediate",
    description: "Prompt injection, filtrado de datos, privacidad, sesgos, red teaming, datasets dorados y evaluación automatizada.",
    whyItMatters: "Un sistema con IA puede fallar de formas no deterministas. Sin evaluación y guardrails no hay confianza operativa.",
    prerequisites: ["Prompt Engineering práctico", "Backend para productos con IA"],
    learn: ["evals", "golden datasets", "guardrails", "tracing", "PII filtering", "adversarial testing"],
    exercises: ["Crea un dataset dorado para RAG", "Evalúa respuestas con rúbricas y métricas simples"],
    resources: ["OWASP LLM Top 10", "Ragas docs", "LangSmith evaluation guides"],
    certifications: ["Microsoft Azure AI Engineer Associate"],
    cloudMappings: [{ concept: "Evaluación y monitoreo", gcp: "Vertex AI Evaluation", aws: "Bedrock Guardrails", azure: "Azure AI Evaluation", local: "Ragas + OpenTelemetry" }],
    nextSkills: ["llmops"],
    position: { x: 900, y: 230 },
  },
  {
    id: "embeddings",
    title: "Embeddings y búsqueda semántica",
    slug: "embeddings-busqueda-semantica",
    category: "RAG",
    level: "intermediate",
    description: "Representación vectorial, chunking, similitud, reranking y casos como búsqueda, recomendación y clasificación.",
    whyItMatters: "Los embeddings conectan conocimiento privado con modelos generales y son la base de RAG, recomendaciones y deduplicación semántica.",
    prerequisites: ["Python para IA", "LLMs e inferencia"],
    learn: ["chunking", "modelos BGE/Nomic", "cosine similarity", "metadata filters", "reranking"],
    exercises: ["Indexa 50 documentos Markdown", "Compara chunking por caracteres vs títulos"],
    resources: ["Sentence Transformers docs", "Qdrant docs", "pgvector docs"],
    certifications: ["Databricks Generative AI Engineer Associate"],
    cloudMappings: [{ concept: "Vector search", gcp: "Vertex AI Vector Search", aws: "OpenSearch Vector Engine", azure: "Azure AI Search", local: "PostgreSQL + pgvector / Qdrant" }],
    nextSkills: ["vector-databases", "rag"],
    position: { x: 540, y: 370 },
  },
  {
    id: "vector-databases",
    title: "Vector databases",
    slug: "vector-databases",
    category: "Data Engineering",
    level: "intermediate",
    description: "Índices vectoriales, filtros por metadata, actualización incremental, particiones, latencia y tradeoffs de almacenamiento.",
    whyItMatters: "La calidad de recuperación depende tanto del modelo de embeddings como de cómo guardas, filtras y actualizas el índice.",
    prerequisites: ["Embeddings y búsqueda semántica", "SQL básico"],
    learn: ["pgvector", "Qdrant", "Chroma", "FAISS", "HNSW", "metadata filtering"],
    exercises: ["Diseña un esquema pgvector para documentos", "Construye una búsqueda híbrida keyword + vector"],
    resources: ["pgvector GitHub", "Qdrant tutorials", "PostgreSQL docs"],
    certifications: ["Databricks Data Engineer Associate"],
    cloudMappings: [{ concept: "Vector DB", gcp: "AlloyDB AI / Vertex Vector Search", aws: "Aurora PostgreSQL + pgvector", azure: "PostgreSQL Flexible Server + pgvector", local: "PostgreSQL + pgvector" }],
    nextSkills: ["rag"],
    position: { x: 540, y: 510 },
  },
  {
    id: "rag",
    title: "RAG e implementación",
    slug: "rag-implementacion",
    category: "RAG",
    level: "intermediate",
    description: "Retrieval Augmented Generation: ingesta, chunking, embedding, retrieval, generación, citas y evaluación.",
    whyItMatters: "RAG permite responder con conocimiento actualizado o privado sin reentrenar modelos, pero exige ingeniería rigurosa de datos y evaluación.",
    prerequisites: ["Embeddings", "Vector databases", "Prompt Engineering práctico"],
    learn: ["pipelines de ingesta", "retrievers", "rerankers", "citaciones", "fallbacks", "evaluación de factualidad"],
    exercises: ["Crea RAG básico sobre documentación interna", "Agrega citas con URL y fragmento fuente"],
    resources: ["LangChain.js docs", "LlamaIndex.TS docs", "Ragas docs"],
    certifications: ["Databricks Generative AI Engineer Associate"],
    cloudMappings: [{ concept: "RAG platform", gcp: "Vertex AI Agent Builder", aws: "Bedrock Knowledge Bases", azure: "Azure AI Search + AI Foundry", local: "LlamaIndex.TS + pgvector" }],
    nextSkills: ["agents-mcp", "llmops"],
    position: { x: 900, y: 440 },
  },
  {
    id: "agents-mcp",
    title: "Agentes, tools y MCP",
    slug: "agentes-tools-mcp",
    category: "Agentes y MCP",
    level: "advanced",
    description: "Diseño de agentes con herramientas, memoria acotada, planificación, permisos, trazas y Model Context Protocol.",
    whyItMatters: "Los agentes convierten modelos en sistemas que actúan. La parte difícil es controlar permisos, errores, costo y observabilidad.",
    prerequisites: ["RAG e implementación", "Backend para productos con IA"],
    learn: ["tool calling", "ReAct", "MCP servers", "human-in-the-loop", "sandboxing", "auditoría"],
    exercises: ["Crea un agente que consulte una API pública", "Expón un MCP server local con una tool segura"],
    resources: ["Model Context Protocol docs", "LangGraph docs", "OpenAI Agents SDK concepts"],
    certifications: ["NVIDIA AI Infrastructure and Operations"],
    cloudMappings: [{ concept: "Agent runtime", gcp: "Vertex AI Agent Engine", aws: "Bedrock Agents", azure: "Azure AI Agent Service", local: "LangGraph + MCP" }],
    nextSkills: ["llmops", "cloud-ai"],
    position: { x: 1260, y: 350 },
  },
  {
    id: "llmops",
    title: "LLMOps y observabilidad",
    slug: "llmops-observabilidad",
    category: "LLMOps",
    level: "advanced",
    description: "Versionado de prompts, evaluación continua, tracing, calidad, costos, incidentes, datasets y gobernanza.",
    whyItMatters: "Cuando una feature IA llega a producción, lo que sostiene el negocio es medir calidad, costo y fallas con disciplina.",
    prerequisites: ["Seguridad, privacidad y evaluación", "RAG e implementación"],
    learn: ["traces", "eval pipelines", "cost dashboards", "prompt registry", "canary releases", "feedback loops"],
    exercises: ["Crea un dashboard de costo por feature", "Implementa una evaluación semanal con GitHub Actions"],
    resources: ["OpenTelemetry", "Langfuse", "Helicone", "Phoenix by Arize"],
    certifications: ["Google Professional Machine Learning Engineer"],
    cloudMappings: [{ concept: "Observability", gcp: "Cloud Monitoring", aws: "CloudWatch", azure: "Azure Monitor", local: "OpenTelemetry + Grafana" }],
    nextSkills: ["cloud-ai", "ai-architectures"],
    position: { x: 1260, y: 510 },
  },
  {
    id: "cloud-ai",
    title: "Cloud AI y plataformas",
    slug: "cloud-ai-plataformas",
    category: "Cloud AI",
    level: "advanced",
    description: "Arquitecturas en GCP, AWS y Azure, equivalencias de servicios, seguridad, IAM, despliegue y costos.",
    whyItMatters: "AI Platform Engineer necesita traducir conceptos de IA a infraestructura operable: redes, identidad, datos, GPU, colas y monitoreo.",
    prerequisites: ["Backend para productos con IA", "LLMOps"],
    learn: ["IAM", "serverless", "containers", "model endpoints", "data governance", "cost controls"],
    exercises: ["Diseña una arquitectura RAG multi-cloud", "Crea una matriz de equivalencias GCP/AWS/Azure"],
    resources: ["Google Cloud Architecture Center", "AWS Well-Architected ML Lens", "Azure Architecture Center"],
    certifications: ["Google Professional Cloud Architect", "AWS Solutions Architect Associate", "Azure AI Engineer Associate"],
    cloudMappings: [{ concept: "AI platform", gcp: "Vertex AI", aws: "Bedrock + SageMaker", azure: "Azure AI Foundry", local: "Docker + Ollama + PostgreSQL" }],
    nextSkills: ["ai-architectures"],
    position: { x: 1620, y: 430 },
  },
  {
    id: "ai-architectures",
    title: "Arquitectura de sistemas IA",
    slug: "arquitectura-sistemas-ia",
    category: "Cloud AI",
    level: "advanced",
    description: "Patrones de arquitectura para productos con IA: RAG empresarial, agentes, pipelines, evals, seguridad y operación.",
    whyItMatters: "AI Architect debe decidir cuándo usar RAG, fine-tuning, agentes, cache, humanos en el loop o modelos locales.",
    prerequisites: ["Cloud AI y plataformas", "LLMOps"],
    learn: ["architecture decision records", "threat modeling", "SLOs de IA", "multi-tenancy", "data contracts"],
    exercises: ["Escribe un ADR para elegir pgvector vs Qdrant", "Diseña un sistema de soporte con RAG, evals y auditoría"],
    resources: ["Microsoft AI Architecture patterns", "AWS Generative AI Lens", "Google Cloud AI patterns"],
    certifications: ["AWS Machine Learning Engineer Associate", "Google Professional Cloud Architect"],
    cloudMappings: [{ concept: "Arquitectura multi-cloud", gcp: "Vertex AI + Cloud Run", aws: "Bedrock + Lambda", azure: "AI Foundry + Container Apps", local: "Coolify/Dokploy + Docker" }],
    nextSkills: [],
    position: { x: 1980, y: 430 },
  },
];

export const certifications: Certification[] = [
  {
    id: "gcp-cloud-digital-leader",
    name: "Google Cloud Digital Leader",
    provider: "Google Cloud",
    level: "beginner",
    url: "https://cloud.google.com/learn/certification/cloud-digital-leader",
    recommendedFor: ["Primer contacto cloud", "Product owners técnicos"],
    relatedSkills: ["intro-ai-engineering", "cloud-ai"],
  },
  {
    id: "gcp-ml-engineer",
    name: "Professional Machine Learning Engineer",
    provider: "Google Cloud",
    level: "advanced",
    url: "https://cloud.google.com/learn/certification/machine-learning-engineer",
    recommendedFor: ["AI Platform Engineer", "AI Architect"],
    relatedSkills: ["llmops", "cloud-ai", "ai-architectures"],
  },
  {
    id: "aws-saa",
    name: "AWS Solutions Architect - Associate",
    provider: "AWS",
    level: "intermediate",
    url: "https://aws.amazon.com/certification/certified-solutions-architect-associate/",
    recommendedFor: ["Cloud Engineer", "AI Architect"],
    relatedSkills: ["cloud-ai", "ai-architectures"],
  },
  {
    id: "aws-mla",
    name: "AWS Certified Machine Learning Engineer - Associate",
    provider: "AWS",
    level: "intermediate",
    url: "https://aws.amazon.com/certification/certified-machine-learning-engineer-associate/",
    recommendedFor: ["AI Engineer", "AI Platform Engineer"],
    relatedSkills: ["rag", "llmops", "cloud-ai"],
  },
  {
    id: "aws-ai-practitioner",
    name: "AWS Certified AI Practitioner",
    provider: "AWS",
    level: "beginner",
    url: "https://aws.amazon.com/certification/certified-ai-practitioner/",
    recommendedFor: ["Primer contacto con IA en AWS", "Backend Engineer → AI Engineer"],
    relatedSkills: ["intro-ai-engineering", "llm-inference", "cloud-ai"],
  },
  {
    id: "aws-machine-learning-specialty",
    name: "AWS Certified Machine Learning - Specialty",
    provider: "AWS",
    level: "advanced",
    url: "https://aws.amazon.com/certification/certified-machine-learning-specialty/",
    recommendedFor: ["ML/AI Engineer avanzado", "AI Platform Engineer"],
    relatedSkills: ["llmops", "cloud-ai", "ai-architectures"],
  },
  {
    id: "azure-ai-engineer",
    name: "Microsoft Certified: Azure AI Engineer Associate",
    provider: "Azure",
    level: "intermediate",
    url: "https://learn.microsoft.com/credentials/certifications/azure-ai-engineer/",
    recommendedFor: ["AI Engineer", "Cloud Engineer"],
    relatedSkills: ["rag", "ai-safety", "cloud-ai"],
  },
  {
    id: "azure-ai-fundamentals",
    name: "Microsoft Certified: Azure AI Fundamentals",
    provider: "Azure",
    level: "beginner",
    url: "https://learn.microsoft.com/credentials/certifications/azure-ai-fundamentals/",
    recommendedFor: ["Fundamentos de IA", "Primer acercamiento a Azure AI"],
    relatedSkills: ["intro-ai-engineering", "llm-inference"],
  },
  {
    id: "azure-ai-apps-agents",
    name: "Microsoft Certified: Azure AI Apps and Agents Developer Associate",
    provider: "Azure",
    level: "intermediate",
    url: "https://learn.microsoft.com/credentials/certifications/azure-ai-apps-and-agents-developer-associate/",
    recommendedFor: ["Agentes", "AI apps con Azure AI Foundry"],
    relatedSkills: ["agents-mcp", "rag", "cloud-ai"],
  },
  {
    id: "gcp-generative-ai-leader",
    name: "Google Cloud Generative AI Leader",
    provider: "Google Cloud",
    level: "beginner",
    url: "https://cloud.google.com/learn/certification/generative-ai-leader",
    recommendedFor: ["Liderazgo técnico", "Fundamentos de IA generativa en Google Cloud"],
    relatedSkills: ["intro-ai-engineering", "prompt-engineering", "cloud-ai"],
  },
  {
    id: "databricks-genai",
    name: "Databricks Generative AI Engineer Associate",
    provider: "Databricks",
    level: "intermediate",
    url: "https://www.databricks.com/learn/certification/generative-ai-engineer-associate",
    recommendedFor: ["Data Engineer", "AI Engineer"],
    relatedSkills: ["embeddings", "vector-databases", "rag"],
  },
  {
    id: "nvidia-genai",
    name: "NVIDIA Generative AI LLMs",
    provider: "NVIDIA",
    level: "intermediate",
    url: "https://www.nvidia.com/en-us/training/",
    recommendedFor: ["AI Engineer", "AI Platform Engineer"],
    relatedSkills: ["llm-inference", "agents-mcp"],
  },
  {
    id: "deeplearning-ai-ml",
    name: "Machine Learning Specialization",
    provider: "DeepLearning.AI / Coursera",
    level: "beginner",
    url: "https://www.coursera.org/specializations/machine-learning-introduction",
    recommendedFor: ["Bases de ML", "Transición desde backend"],
    relatedSkills: ["intro-ai-engineering", "python-ai"],
  },
  {
    id: "deeplearning-ai-prompt",
    name: "DeepLearning.AI Prompt Engineering for Developers",
    provider: "DeepLearning.AI / Coursera",
    level: "beginner",
    url: "https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/",
    recommendedFor: ["Prompt engineering", "Backend Engineer → AI Engineer"],
    relatedSkills: ["prompt-engineering", "llm-inference"],
  },
  {
    id: "aws-developer-associate",
    name: "AWS Certified Developer - Associate",
    provider: "AWS",
    level: "intermediate",
    url: "https://aws.amazon.com/certification/certified-developer-associate/",
    recommendedFor: ["Backend para IA", "Serverless en AWS"],
    relatedSkills: ["backend-ai", "cloud-ai"],
  },
  {
    id: "azure-developer-associate",
    name: "Azure Developer Associate",
    provider: "Azure",
    level: "intermediate",
    url: "https://learn.microsoft.com/credentials/certifications/azure-developer/",
    recommendedFor: ["Backend para IA", "Serverless en Azure"],
    relatedSkills: ["backend-ai", "cloud-ai"],
  },
  {
    id: "gcp-cloud-architect",
    name: "Google Professional Cloud Architect",
    provider: "Google Cloud",
    level: "advanced",
    url: "https://cloud.google.com/learn/certification/cloud-architect",
    recommendedFor: ["AI Architect", "Cloud AI"],
    relatedSkills: ["cloud-ai", "ai-architectures"],
  },
  {
    id: "nvidia-ai-infrastructure",
    name: "NVIDIA AI Infrastructure and Operations",
    provider: "NVIDIA",
    level: "advanced",
    url: "https://www.nvidia.com/en-us/training/",
    recommendedFor: ["AI Platform Engineer", "Infraestructura para agentes y LLMs"],
    relatedSkills: ["agents-mcp", "llmops", "cloud-ai"],
  },
];

export const resources: Resource[] = [
  {
    id: "roadmap-ai-engineer",
    title: "Roadmap AI Engineer de roadmap.sh",
    type: "docs",
    url: "https://roadmap.sh/ai-engineer",
    provider: "roadmap.sh",
    relatedSkills: ["intro-ai-engineering"],
    difficulty: "beginner",
  },
  {
    id: "hugging-face-agents-course",
    title: "Hugging Face AI Agents Course",
    type: "course",
    url: "https://huggingface.co/learn/agents-course/",
    provider: "Hugging Face",
    relatedSkills: ["intro-ai-engineering", "agents-mcp"],
    difficulty: "intermediate",
  },
  {
    id: "google-ml-crash-course",
    title: "Google Machine Learning Crash Course",
    type: "course",
    url: "https://developers.google.com/machine-learning/crash-course",
    provider: "Google",
    relatedSkills: ["intro-ai-engineering", "python-ai"],
    difficulty: "beginner",
  },
  {
    id: "fastapi-docs",
    title: "FastAPI docs",
    type: "docs",
    url: "https://fastapi.tiangolo.com/",
    provider: "FastAPI",
    relatedSkills: ["python-ai", "backend-ai"],
    difficulty: "beginner",
  },
  {
    id: "pydantic-docs",
    title: "Pydantic docs",
    type: "docs",
    url: "https://docs.pydantic.dev/",
    provider: "Pydantic",
    relatedSkills: ["python-ai"],
    difficulty: "beginner",
  },
  {
    id: "python-packaging",
    title: "Python Packaging User Guide",
    type: "docs",
    url: "https://packaging.python.org/",
    provider: "Python Packaging Authority",
    relatedSkills: ["python-ai"],
    difficulty: "beginner",
  },
  {
    id: "next-route-handlers",
    title: "Next.js Route Handlers",
    type: "docs",
    url: "https://nextjs.org/docs/app/building-your-application/routing/route-handlers",
    provider: "Next.js",
    relatedSkills: ["backend-ai"],
    difficulty: "intermediate",
  },
  {
    id: "vercel-functions",
    title: "Vercel Functions docs",
    type: "docs",
    url: "https://vercel.com/docs/functions",
    provider: "Vercel",
    relatedSkills: ["backend-ai"],
    difficulty: "intermediate",
  },
  {
    id: "opentelemetry",
    title: "OpenTelemetry docs",
    type: "docs",
    url: "https://opentelemetry.io/docs/",
    provider: "OpenTelemetry",
    relatedSkills: ["backend-ai", "llmops"],
    difficulty: "intermediate",
  },
  {
    id: "prompt-engineering-guide",
    title: "Prompt Engineering Guide",
    type: "docs",
    url: "https://www.promptingguide.ai/",
    provider: "DAIR.AI",
    relatedSkills: ["prompt-engineering"],
    difficulty: "beginner",
  },
  {
    id: "mcp-docs",
    title: "Model Context Protocol",
    type: "docs",
    url: "https://modelcontextprotocol.io/",
    provider: "MCP",
    relatedSkills: ["agents-mcp"],
    difficulty: "advanced",
  },
  {
    id: "pgvector",
    title: "pgvector",
    type: "repo",
    url: "https://github.com/pgvector/pgvector",
    provider: "PostgreSQL",
    relatedSkills: ["vector-databases", "rag"],
    difficulty: "intermediate",
  },
  {
    id: "sentence-transformers",
    title: "Sentence Transformers",
    type: "docs",
    url: "https://www.sbert.net/",
    provider: "UKP Lab",
    relatedSkills: ["embeddings"],
    difficulty: "intermediate",
  },
  {
    id: "qdrant-docs",
    title: "Qdrant docs",
    type: "docs",
    url: "https://qdrant.tech/documentation/",
    provider: "Qdrant",
    relatedSkills: ["vector-databases", "embeddings"],
    difficulty: "intermediate",
  },
  {
    id: "qdrant-tutorials",
    title: "Qdrant tutorials",
    type: "docs",
    url: "https://qdrant.tech/documentation/tutorials/",
    provider: "Qdrant",
    relatedSkills: ["vector-databases"],
    difficulty: "intermediate",
  },
  {
    id: "postgresql-docs",
    title: "PostgreSQL docs",
    type: "docs",
    url: "https://www.postgresql.org/docs/",
    provider: "PostgreSQL",
    relatedSkills: ["vector-databases"],
    difficulty: "intermediate",
  },
  {
    id: "langchain-js",
    title: "LangChain.js",
    type: "docs",
    url: "https://js.langchain.com/",
    provider: "LangChain",
    relatedSkills: ["rag", "agents-mcp"],
    difficulty: "intermediate",
  },
  {
    id: "llamaindex-ts",
    title: "LlamaIndex.TS docs",
    type: "docs",
    url: "https://ts.llamaindex.ai/",
    provider: "LlamaIndex",
    relatedSkills: ["rag"],
    difficulty: "intermediate",
  },
  {
    id: "ragas-docs",
    title: "Ragas docs",
    type: "docs",
    url: "https://docs.ragas.io/",
    provider: "Ragas",
    relatedSkills: ["rag", "ai-safety"],
    difficulty: "intermediate",
  },
  {
    id: "owasp-llm",
    title: "OWASP Top 10 for LLM Applications",
    type: "docs",
    url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
    provider: "OWASP",
    relatedSkills: ["ai-safety"],
    difficulty: "intermediate",
  },
  {
    id: "owasp-llm-short",
    title: "OWASP LLM Top 10",
    type: "docs",
    url: "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
    provider: "OWASP",
    relatedSkills: ["ai-safety", "prompt-engineering"],
    difficulty: "intermediate",
  },
  {
    id: "langgraph-docs",
    title: "LangGraph docs",
    type: "docs",
    url: "https://langchain-ai.github.io/langgraph/",
    provider: "LangChain",
    relatedSkills: ["agents-mcp"],
    difficulty: "advanced",
  },
  {
    id: "ollama-library",
    title: "Ollama model library",
    type: "docs",
    url: "https://ollama.com/library",
    provider: "Ollama",
    relatedSkills: ["llm-inference"],
    difficulty: "beginner",
  },
  {
    id: "huggingface-open-llm",
    title: "Hugging Face Open LLM Leaderboard",
    type: "docs",
    url: "https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard",
    provider: "Hugging Face",
    relatedSkills: ["llm-inference"],
    difficulty: "beginner",
  },
  {
    id: "lmsys-arena",
    title: "LMSYS Chatbot Arena",
    type: "docs",
    url: "https://lmarena.ai/",
    provider: "LMArena",
    relatedSkills: ["llm-inference"],
    difficulty: "beginner",
  },
];

export const learningPaths: LearningPath[] = [
  {
    id: "backend-to-ai-engineer",
    title: "Backend Engineer → AI Engineer",
    audience: "Backend developers que ya dominan APIs y quieren sumar LLMs, RAG y evals.",
    description: "Ruta corta desde producto y APIs hacia features con IA listas para producción.",
    skills: ["intro-ai-engineering", "python-ai", "backend-ai", "llm-inference", "prompt-engineering", "embeddings", "rag", "ai-safety", "llmops"],
  },
  {
    id: "data-to-ai-engineer",
    title: "Data Engineer → AI Engineer",
    audience: "Data engineers con experiencia en pipelines, SQL y calidad de datos.",
    description: "Aprovecha bases de datos y pipelines para dominar embeddings, RAG y evaluación.",
    skills: ["intro-ai-engineering", "python-ai", "embeddings", "vector-databases", "rag", "ai-safety", "llmops", "cloud-ai"],
  },
  {
    id: "cloud-to-platform",
    title: "Cloud Engineer → AI Platform Engineer",
    audience: "Cloud engineers que quieren operar plataformas internas de IA.",
    description: "Enfatiza serverless, seguridad, costos, observabilidad y equivalencias cloud.",
    skills: ["intro-ai-engineering", "backend-ai", "llm-inference", "vector-databases", "rag", "agents-mcp", "llmops", "cloud-ai", "ai-architectures"],
  },
  {
    id: "ai-to-architect",
    title: "AI Engineer → AI Architect",
    audience: "AI Engineers que ya construyen features y quieren tomar decisiones de arquitectura.",
    description: "Eleva de implementación a arquitectura, gobernanza y decisiones multi-cloud/open-source.",
    skills: ["rag", "agents-mcp", "ai-safety", "llmops", "cloud-ai", "ai-architectures"],
  },
];

export const playgroundExercises: PlaygroundExercise[] = [
  {
    id: "embedding-api",
    title: "Construir API de embeddings",
    level: "beginner",
    objective: "Exponer un endpoint que reciba texto, devuelva un vector mock y registre metadata.",
    deliverables: ["Route Handler", "contrato TypeScript", "tests de payload inválido"],
    stack: ["Next.js", "TypeScript", "SQLite mock"],
    relatedSkills: ["backend-ai", "embeddings"],
  },
  {
    id: "basic-rag",
    title: "Crear RAG básico",
    level: "intermediate",
    objective: "Ingestar documentos, partirlos en chunks, recuperar los top-k y construir una respuesta con citas.",
    deliverables: ["pipeline de ingesta", "retriever", "respuesta con fuentes"],
    stack: ["LangChain.js", "pgvector futuro", "Markdown"],
    relatedSkills: ["embeddings", "vector-databases", "rag"],
  },
  {
    id: "llm-evals",
    title: "Evaluar respuestas de un LLM",
    level: "intermediate",
    objective: "Crear un dataset dorado y una rúbrica simple de exactitud, completitud y seguridad.",
    deliverables: ["dataset JSON", "script de evaluación", "reporte de regresión"],
    stack: ["TypeScript", "GitHub Actions", "Ragas futuro"],
    relatedSkills: ["ai-safety", "llmops"],
  },
  {
    id: "agent-tools",
    title: "Crear agente con tools",
    level: "advanced",
    objective: "Diseñar un agente que pueda consultar una API y pedir confirmación antes de acciones sensibles.",
    deliverables: ["tool schema", "traces", "human-in-the-loop"],
    stack: ["MCP", "LangGraph futuro", "Node.js"],
    relatedSkills: ["agents-mcp", "backend-ai"],
  },
  {
    id: "multi-cloud-architecture",
    title: "Diseñar arquitectura multi-cloud",
    level: "advanced",
    objective: "Comparar GCP, AWS, Azure y una alternativa self-hosted para un producto RAG empresarial.",
    deliverables: ["diagrama C4", "ADR", "matriz de costos/riesgos"],
    stack: ["Vertex AI", "Bedrock", "Azure AI", "Ollama"],
    relatedSkills: ["cloud-ai", "ai-architectures"],
  },
  {
    id: "inference-costs",
    title: "Monitorear costos de inferencia",
    level: "intermediate",
    objective: "Registrar tokens, latencia y errores por feature para detectar regresiones de costo.",
    deliverables: ["modelo de eventos", "dashboard mock", "alertas sugeridas"],
    stack: ["OpenTelemetry", "SQLite", "Grafana futuro"],
    relatedSkills: ["llm-inference", "llmops"],
  },
];

export const categories = Array.from(new Set(skills.map((skill) => skill.category)));
export const levels = ["beginner", "intermediate", "advanced"] as const;
